version: '3.3'
services:
    mongo:
        image: mongo
        volumes:
            - ${HOME}/.pathsports-mongodb-data:/data/db
        ports:
            - 37018:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongoadmin
            - MONGO_INITDB_ROOT_PASSWORD=mongopass
        tty: true
